### Run starsolo/scTE mapping and quantitation on 10X scRNA-seq data 
### Date: 2022-10-04
### Alec Pankow (@alecpnkw), adapted from Roosheel Patel (@roosheelpatel)

from snakemake.utils import min_version
import pandas as pd
from os.path import dirname, basename
min_version("8.0")

configfile: "config/config-IFN_A.yaml"
localrules: all, scte_install, scte_build

# targeting rule
rule all:
   input:
      "results/irescue/IFN_A_hg38"

rule irescue:
   input:
      "results/clean_bam/{dataset}_{genome}/Aligned.sortedByCoord.out.bam"
   output:
      directory("results/irescue/{dataset}_{genome}")
   params:
      genome = lambda wc: wc.genome,
      whitelist = config["umi_whitelist"]
   conda: "envs/irescue.yaml"
   threads: 8
   resources:
      mem_mb = 80000,
      disk_mb = 164000,
      walltime = 12:00
   shell:
      """
      irescue \
      --bam {input} \
      --genome {params.genome} \
      --outdir {output} \
      -p {threads} \
      --whitelist {params.whitelist} \
      --keeptmp
      """

include: "rules/starsolo.smk"
include: "rules/scTE.smk"
