### Run starsolo/scTE mapping and quantitation on 10X scRNA-seq data 
### Date: 2022-10-04
### Alec Pankow (@alecpnkw), adapted from Roosheel Patel (@roosheelpatel)

from snakemake.utils import min_version
import pandas as pd
from os.path import dirname, basename
min_version("8.0")

configfile: "config/config-series2.yaml"
localrules: all, scte_install, scte_build

# read in samples file
samples = pd.read_csv(config["samples"], sep=',', header=0).set_index("fastq_id", drop=False)

# targeting rule
rule all:
   input:
      expand("results/irescue/{dataset}_{genome}", dataset = samples.index, genome = config["genome"]["name"])

rule irescue:
   input:
      "results/clean_bam/{dataset}_{genome}/Aligned.sortedByCoord.out.bam"
   output:
      directory("results/irescue/{dataset}_{genome}")
   params:
      genome = "hg38", #fixing this as human genome build for now, may throw an error with PR8 concat genome
      whitelist = config["umi_whitelist"]
   conda: "envs/irescue.yaml"
   threads: 8
   resources:
      mem_mb = 80000,
      disk_mb = 164000,
      walltime = 720
   shell:
      """
      irescue \
      --bam {input} \
      --genome {params.genome} \
      --outdir {output} \
      -p {threads} \
      --whitelist {params.whitelist} \
      --keeptmp
      """

include: "rules/starsolo.smk"
include: "rules/scTE.smk"
